### ISSUE TITLE
ctre bindings generation

### ISSUE THREAD

**Issue by virtuald** [Lytigas/first-rust-competition#1]
I'm not volunteering to help, but you may find the tool that RobotPy uses to generate bindings (or a variation of that approach) useful.

https://github.com/robotpy/robotpy-ctre/tree/master/gen

**Comment by Redrield** [comment]
@virtuald https://github.com/auscompgeek/ctre-rs may be of interest.

**Comment by auscompgeek** [comment]
Heh. I'm presuming Dustin did see me create ctre-rs in his GitHub feed. Funny how this issue only predates my work by a few days.

**Comment by virtuald** [comment]
Haha, did you create it independent of this issue?

**Comment by auscompgeek** [comment]
I didn't even know this project existed until yesterday!
