### ISSUE TITLE
Relicense wpilib crate

### ISSUE THREAD

**Issue by auscompgeek** [Lytigas/first-rust-competition#16]
*See-also: #8 (C-PERMISSIVE)*

As was brought up in #8, the GPLv3 is *not* a permissive license, and forces downstream users to also license their code under GPLv3 when redistributing their source code.

This in particular badly affects ctre-rs, where this scenario effectively creates a crayon license in the scenario where a user links with this crate (which will be the default).

The Rust libs team recommends dual-licensing libraries under MIT/Apache2. Upstream WPILib is licensed under 3-BSD.

**Comment by Lytigas** [comment]
I suppose it is easier for the community if I cede on this one and relicense under MIT and Apache 2.0.

I'll need consent from @jmeggit, @auscompgeek, and @bookofportals for this.

**Comment by jmeggitt** [comment]
@auscompgeek - ["The Rust libs team recommends dual-licensing libraries under MIT/Apache2"](https://github.com/Lytigas/first-rust-competition/issues/16)
@bookofportals - ["please seriously consider dual MIT/Apache"](https://github.com/Lytigas/first-rust-competition/issues/8)
@jmeggitt - Sounds good to me.

**Comment by Lytigas** [comment]
@jmeggitt Really I was looking for something like "Yes I agree to relicense my contributions under MIT/Apache 2.0"

@auscompgeek not that it matters, but Apache 2.0 is compatible with [GPLv3 but not v2](https://www.gnu.org/licenses/license-list.en.html#apache2)

**Comment by auscompgeek** [comment]
Bah, my memory fails me. Darn off-by-one errors. Makes more sense that way around though.

FYI, LGPL would also be acceptable to me, and I don't really expect any teams to object to the use of *GPL code.

Taking another look at my contributions, they've been pretty minimal, and `DigitalInput::new` was pretty much a copy-paste anyway, so I guess I don't really care about copyright on my code so far...

I hereby waive my copyright claims on my past contributions to this project.

**Comment by jmeggitt** [comment]
Yes I agree to relicense my contributions under MIT/Apache 2.0

**Comment by bookofportals** [comment]
I agree to license all my past and future contributions MIT/Apache 2.0.

**Comment by bookofportals** [comment]
@auscompgeek Personally, I tend to go with LGPL too (sometimes MIT), but if the ecosystem has a standard, it's best to fit in.
