### ISSUE TITLE
Cannot report usage of multiple hardware devices

### ISSUE THREAD

**Issue by auscompgeek** [Lytigas/first-rust-competition#3]
The safe interface exposed here in `wpilib::hal::usage` doesn't allow for specifying instances of resources associated to ports such as PWM channels, and devices with arbitrary IDs.

**Comment by Lytigas** [comment]
I think this code covers that?
```rust
/// A safe wrapper around HAL_Report
pub fn report_usage_extras(
    resource: UsageResourceType,
    instance: UsageResourceInstance,
    context: i32,
    feature: *const raw::c_char,
) {
    unsafe {
        HAL_Report(resource as i32, instance as i32, context, feature);
    }
}
```
Rust has no function overloading though, so the name has to be different.

If there's some HAL function that there isn't an interface for, please show it to me!

**Comment by auscompgeek** [comment]
Oh, right, `nUsageReporting_tInstances` is an alias of `u32`? Yeah, I guess that works then. That's totally not confusing at all :stuck_out_tongue_winking_eye:
