### ISSUE TITLE
impl std::io::{Read, Write} for SerialPort

### ISSUE THREAD

**Issue by auscompgeek** [Lytigas/first-rust-competition#30]
It'd probably make sense to make SerialPort a reader and writer. Fundamentally it is at least, so this should be reflected in its interface.

This would also give the entire Rust ecosystem around `std::io` (such as the `byteorder` crate) for free.

**Comment by auscompgeek** [comment]
Should be noted as well that currently the docs are very misleading about what type SerialPort takes.

**Comment by Lytigas** [comment]
Is #31 what you were looking for?

**Comment by auscompgeek** [comment]
Looks alright.

The termination is a good point I suppose, but at the same time I guess any weird filesystem could perform similar tricks.
