### ISSUE TITLE
PWMSpeedController as a trait?

### ISSUE THREAD

**Issue by Redrield** [Lytigas/first-rust-competition#32]
From what I've seen of the implementation, PWMSpeedController is a struct that is going to represent every PWM controller, sounds like a job for a trait (Though I don't know how homogeneous the PWM motor controller impl details in wpilib are so maybe it would be the right choice)

**Comment by Lytigas** [comment]
My working understanding is that all PWMSpeedControllers are identical save for the mapping of percentage to duty cycle (max, min, etc).

**Comment by Lytigas** [comment]
I'm going for more of a minimal safe hardware layer than a framework like WPILib. If someone wanted to make a series of traits for this sort of thing like [alga](https://crates.io/crates/alga), I would be down to provide trait impls.

**Comment by Redrield** [comment]
Then why is the crate called wpilib if it's not looking to provide a framework equivalent to wpilib?
