### ISSUE TITLE
Library deploy location is moving in 2019

### ISSUE THREAD

**Issue by auscompgeek** [Lytigas/first-rust-competition#39]
Just a heads-up, I've received word from the WPILib devs that third-party libraries should be deployed to `/usr/local/frc/third-party/lib` for next season. This includes the WPILib libraries such as the HAL and wpiutil.

**Comment by auscompgeek** [comment]
I'm not aware of any changes necessary to start scripts.

**Comment by Lytigas** [comment]
Thanks for the information!
