### ISSUE TITLE
Re-architect DriverStation

### ISSUE THREAD

**Issue by Lytigas** [Lytigas/first-rust-competition#6]

**Comment by auscompgeek** [comment]
Would fix the clippy warnings, I guess.

**Comment by Lytigas** [comment]
I'm not very happy with how things are right now. People will need to write their own main loop, most likely a thread that calls `wait_for_data`, but that requires owning the same `RwLock` (the one in `ThreadSafeDS`) as the updater thread. I haven't tested it yet, but a deadlock seems likely.

Regardless, the current code isn't great. I think the best alternative is a lockless "pub-sink" where subscribes get their own `(Arc<Mutex>, Arc<Condvar>)` The `DriverStation` stores `Weak<Mutex>`s in a vector, puts data into them, and then `condvar.notify_all()`. This has the issue of possibly delaying other sink's updates if data is being read as a packet is received, but as long as each lock is held for less than 50ms, there shouldn't be much contention; other sinks can be updated while we wait.

The lockless version of that is something like
```rust
pub struct DsDataSubscriber {
    rec: Receiver<DsData>
    cache: DsData
}
```
where each read tries to update the cache using the latest data from the channel, if there is any. I like having the option of a Condvar for user input loops, though.

Anyone else have ideas?

**Comment by bookofportals** [comment]
Pardon, but couldn't you do both at once? I don't much like the idea of the `(Arc<Mutex>, Arc<Condvar>)`, because forcing your users to deal with something as low level as a `Condvar` feels messy. What about something like this (sorry if I'm missing something obvious here):
```rust
// I hereby release this code under the MIT license
pub struct CachedSubscription<T> {
    rec: Receiver<T>,
    cache: T,
    cond: Condvar,
    mutex: Mutex<()>,
}

impl<T> CachedSubscription<T> {
    pub fn get_latest(&mut self) -> &T {
        match self.rec.try_iter().last() {
            Some(item) => self.cache = item,
            None => (),
        }
        &self.cache
    }

    pub fn wait(&mut self) -> &T {
        let lock = self.mutex.lock().unwrap();

        // this implementation is bad because it does not deal with spurious wakeups
        match self.cond.wait(lock) {
            Ok(_) => (),
            Err(_) => panic!("Posioned mutex!"),
        };

        self.get_latest()
    }
}
```

It's generic because this is a generally useful concurrency primitive. I'd toss it in a util module somewhere, and if it turns out to be very useful maybe eventually give it its own crate.

**Comment by jmeggitt** [comment]
Well what exactly is ```DsData```? The user never directly gets data from the driver station. They use Joysticks which then reference the driver station. So why force them to use the extra complication?

```rust
// Robot contains init for everything including driver station
// Driver station can use lazy-static 
let robot = Robot::new().expect("Could not create robot!");

// These go to the driver station
robot.subscribe_teleop(/* My super amazing teleop function! */);
robot.subscribe_auton(/* My super amazing autonomous function! */);
```

```rust
// Contains all of the data previously in DriverStation
pub struct DsData {
    joysticks: Joysticks,
    control_word: HAL_ControlWord,
    state: RobotState,
    fms_attached: bool,
    ds_attached: bool,
    report_throttler: Throttler<u64, u64>,
    condvar: Arc<(Mutex<bool>, Condvar)>,
    join: Option<thread::JoinHandle<()>>,
}

pub struct DriverStation {
    data: whatEverConcurrencyModel<DsData>,
}

impl DriverStation {
    
    // Get the lock so that if someone wants to be able to use more concurrency can
    pub fn get_lock(&self) -> whatEverConcurrencyModel<DsData> {
        self.data
    }

    // Main update loop started when Robot::new() is called.
    fn loopy_stuff(&self) {
        loop {
            self.wait_for_data();
            // update stuff...
        }
    }

    // Handle concurrency in middle layer.
    pub fn get_joystick_axis(&self, stick: usize, axis: usize) -> Result<f32, JoystickError> {
        self.data.lockStuff().upwrap().get_joystick_axis(stick, axis)
    }
}

impl DsData {
    // Uses the basic data methods of DriverStation
    fn update_data(&mut self, control_word: HAL_ControlWord);
    pub fn get_joystick_axis(&self, stick: usize, axis: usize) -> Result<f32, JoystickError>;
    // etc...
}
```

**Comment by Lytigas** [comment]
@jmeggitt `DsData` includes things like what team the robot is on, what alliance station they're at, the "Game Data" string etc.

**Comment by jmeggitt** [comment]
Okay, I think my solution still works then.
