### ISSUE TITLE
Links to other FRC related projects

### ISSUE THREAD

**Issue by Redrield** [Lytigas/first-rust-competition#7]
Linking to other projects to do with FRC to give people who want to experiment a better idea of what's available would be nice (just in the README)

- @auscompgeek 's [ctre-rs](https://github.com/auscompgeek/ctre-rs)
- my [nt-rs](https://gitlab.com/Redrield/nt-rs)

**Comment by auscompgeek** [comment]
There's a link to ctre-rs in the wpilib README. It's probably not very obvious though, buried in a wall of text.

**Comment by jmeggitt** [comment]
[EagleStrike](https://github.com/Eaglestrike) has been working on full rust support. We have [navX-rs](https://github.com/Eaglestrike/navX-rs) support and have been working on a rust implementation of our robot.

**Comment by Lytigas** [comment]
Thanks for the great idea!
