### ISSUE TITLE
Cannot report usage from other crates

### ISSUE THREAD

**Issue by auscompgeek** [Lytigas/first-rust-competition#9]

**Comment by Lytigas** [comment]
I'm not quite sure how to expose the constants themselves without exposing all the bindings. This is kind of making me want to split the bindings into a `wpilib-sys` crate. Any ideas?

**Comment by auscompgeek** [comment]
> This is kind of making me want to split the bindings into a wpilib-sys crate.

This is probably the best way to go about it, as then ctre-rs wouldn't have to depend on the entirety of the wpilib crate, and if people don't like some of the wpilib implementation here, they would be able to write their own.
